services:
  - type: web
    name: tco-calculator-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CORS_ORIGINS
        value: https://kapil433.github.io
    plan: free
